name: Deploy Angular to GitHub Pages

on:
  push:
    branches:
      - main  # Deploys when code is pushed to "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18  # Compatible with Angular 11

      - name: Install dependencies
        run: npm install

      - name: Install Angular CLI (Specific Version)
        run: npm install -g @angular/cli

      - name: Build Angular app
        run: ng build --output-path=dist --base-href /movie-ticket-booking/

      - name: Deploy to GitHub Pages
        uses: AhsanAyaz/angular-deploy-gh-pages-actions@v3
        with:
          branch: gh-pages  # Deploy to gh-pages branch
          folder: dist  # Ensure the correct folder is used
